### ISSUE TITLE
Improve webclient error handling 

### ISSUE THREAD

**Issue by jarlehansen** [FINTLabs/fint-graphql#5]
Errors in webclient, such as wrong url when getting the linked resource, results in `internal server error`:  
```
{
  "data": {
    "arbeidsforhold": null
  },
  "errors": [
    {
      "message": "Internal Server Error(s) while executing query",
      "path": null,
      "extensions": null
    }
  ]
}
```

This should be handled better, returning a proper error message to the client.

**Comment by asgeirn** [comment]
Fixed.
